# Generated by Django 4.0.5 on 2022-08-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('relationship', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('phone_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
